version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-application
    container_name: ras-shoper
    env_file: .env.docker-dev
    entrypoint: /developermode
    ports:
      - 8080:80
    depends_on:
      - db
      - cache
    volumes:
      - .:/var/www/html
